[project]
name = "klines"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "httpx[http2]>=0.28.1",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
]

[dependency-groups]
lint = ["pyright>=1.1.397", "ruff>=0.11.0"]
